### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ghost** [Samuel-Harwood/CMP1903M-Assessment-1-Base-Code#2]
# Error overview

- In most cases of the program's error handling, whenever some check fails, it calls `Program.Main` to recursively retry until all checks passes. This can be a problem since if a user inputs many things and makes a mistake later, they will have to redo all inputs again to reach that point again.
Since the program is also made as an application, it should try it's best to create a human readable error to notify the user what went wrong, and handle the error accordingly to avoid crashing the application entirely, which this `catch` statement doesn't do.
Although it will almost be unlikely, it can still cause a `StackOverFlowException` with enough fails.

`Program.cs`
- The `Main` method has a huge [`try`](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L22) surrounding the whole program, and returns the exception to the console. This works but the exception message can be confusing for the application user rather than be helpful.
- The `Main` method creates a local variable called `Manual` which is directly assigning a value from `Console.ReadLine` but doesn't handle the `null` variable.
- The `Main` method handles input mode error with an if statement and lets the user know that the input mode is invalid [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L42).

`Analyse.cs`
- The `Analysis` method has a basic input error handling for when there is no input [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Analyse.cs#L18) which lets the user know if something went wrong and handles the error properly.

`Input.cs`
- The functions `ManualTextInput` and `FileTextInput` creates a local variable `isCorrect` [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Input.cs#L21) and [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Input.cs#L48) which is directly assigned from `Console.ReadLine()`, which has a possibility of returning `null`, which is unhandled in the code.

# Structure
- The program first handles the input mode of `manual input` or `file input`, then proceeds to check if the read content is correct to the user, and analyses the input, which then the analysis result is written to the console and returns the file 

`Analyse.cs`
- The class contains the function `Analysis` handles all the analysing, as well as the [file outputting](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Analyse.cs#L141) and [reporting](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Analyse.cs#L146), which can get confusing as a single function since more functionality can get added in the future.
- A reporting is done in the `Analysis` [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Analyse.cs#L141) instead of separating into the `Report` class for it to handle.

`Input.cs`
- The `FileTextInput` function requires the file path as an argument, but instead the program is supplying it the text file contents directly [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L38).
- Both of the input functions can jump to `Program.Main` or call `Analyse.Analysis`, which can be misleading for other contributers on what's happening with the program flow.

`Report.cs`
- The `Reports` function formats the result very clean in different lines for each category [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Report.cs#L17).

`Program.cs`
- The user is able to choose if they want to enter the text manually or through a text file, however, the text file input has a hardcoded path, which might not be convenient for the user [here](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L38).

# Commenting
- The program has enough comments for me to understand what parts of the function do what.

# Changes
- Instead of a recursive call to `Program.Main` when the user makes a mistake or something goes wrong, it will use a while loop to keep trying until the user inputs something valid.
- Changed [FileTextInput](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/d5d5f4bce19c9db1f8aedf2d30f032ff7a31d103/CMP1903M%20Assessment%201%20Base%20Code/Input.cs#L44) to take a file path instead of an input that's already read.
- `Input.cs` methods return a "success status" which lets you know if the input was correct or not.
- Separated functionality of analysing the input and reporting the input into a new function.

**Comment by ghost** [comment]
commits for the [changes](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/pull/3)

**Comment by Samuel-Harwood** [comment]
Added Dictionary to `Report.cs`
Added Switch statements to `Program.cs`
Added Private Variables
Removed Static methods from classes
Update to File Path finder
General Fixes
