### ISSUE TITLE
Code Review-Samuel Broadhurst

### ISSUE THREAD

**Issue by SamB2187** [Samuel-Harwood/CMP1903M-Assessment-1-Base-Code#4]
<img width="355" alt="Review" src="https://user-images.githubusercontent.com/78020133/159944086-8f1430d0-966d-41ac-a18e-ed8d736dfe6a.PNG">
I noticed this in your analyse code and went to test it too and found out that you only count sentences that end with a full stop. I would suggest making it is able to recognize other sentence enders such as a question mark or exclamation mark. If not your analyse could result in the following:
<img width="526" alt="Review2" src="https://user-images.githubusercontent.com/78020133/159944199-fb009f47-2e43-413f-b2ed-005aaac87c80.PNG">

**Comment by Samuel-Harwood** [comment]
`Analyse.cs` [Sentence Count](https://github.com/Samuel-Harwood/CMP1903M-Assessment-1-Base-Code/blob/372c83a3936f8f917b464b09771b059a902d45e4/CMP1903M%20Assessment%201%20Base%20Code/Analyse.cs#L37) has been modified to incorporate characters: ".?!"
